### ISSUE TITLE
Link broken in challenge_post.md

### ISSUE THREAD

**Issue by matheusfaustino** [mozillascience/fellows-class-2015#23]
Hi,

I was reading the file "[explore/1-challenge_post.md](https://github.com/mozillascience/fellows-class-2015/blob/master/explore/1-challenge_post.md)" and the link "[challenge exercise](https://github.com/mozillascience/fellows-class-2015/blob/master/challenge_exercise.md)" is broken.

Maybe the name of the file was changed.

Best,

**Comment by blahah** [comment]
Thanks for the bug report and the fix!

![](https://media.giphy.com/media/3osxYdXvsGw6wT5lIY/giphy.gif)
