### ISSUE TITLE
Complete Intro Interview and Provide Audio

### ISSUE THREAD

**Issue by zee-moz** [mozillascience/fellows-class-2015#4]
Complete your assigned interview and upload the audio file to Dropbox. We'll have the interview transcribed and get back to you with the transcript file as soon as it's ready. 
- [x] Christie Interviews Joey, uploads file
- [x] Joey Interviews Richard, uploads file
- [x] Richard Interviews Jason, uploads file
- [x] Jason Interviews Christie, uploads file

**Comment by Blahah** [comment]
:) unfortunately only one of us can be assigned at a time!

**Comment by zee-moz** [comment]
@cbahlai @Blahah @jasonbobe please complete and check off!

**Comment by jasonbobe** [comment]
back in action today, gitter has deets

**Comment by blahah** [comment]
All done!
