### ISSUE TITLE
Log in to MSL's Wordpress Blog and Create a DRAFT of your Problem/Challenge Post

### ISSUE THREAD

**Issue by zee-moz** [mozillascience/fellows-class-2015#5]
Instructions on [Challenge Post](https://github.com/mozillascience/fellows-class-2015/blob/master/challenge_post.md) are here! Don't publish your post just yet... we'll publish the interviews first, then the challenge posts... First round should go out sometime week of 12/7. Check yourself off when you're done!
- [x] Christie
- [x] Joey
- [x] Jason
- [x] Richard

**Comment by abbycabs** [comment]
Logins have been emailed out!

Login here: http://wp.mozillascience.org/wp-login.php

**Comment by zee-moz** [comment]
@Blahah @joeyklee @cbahlai @jasonbobe

**Comment by auremoser** [comment]
@jasonbobe did you finish your challenge post? feel free to update the issue!
